# Generated by Django 3.0.4 on 2020-03-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('info', models.TextField(default='No information available')),
            ],
        ),
        migrations.CreateModel(
            name='QuizCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(default='general', max_length=255)),
                ('subject', models.CharField(default='general paper', max_length=255)),
                ('image', models.CharField(max_length=50)),
                ('allocated_time', models.IntegerField(default=10)),
                ('rating', models.CharField(default='normal', max_length=50)),
                ('date', models.DateField(default='Fri Mar 20 07:48:18 2020')),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tquiz.Examiner')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('quiz_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tquiz.QuizCatalog')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tquiz.Question')),
            ],
        ),
    ]
