# Generated by Django 3.0.4 on 2020-03-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tquiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='quizcatalog',
            name='subject',
        ),
        migrations.AddField(
            model_name='quizcatalog',
            name='level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='quizcatalog',
            name='programme',
            field=models.CharField(default='general', max_length=255),
        ),
        migrations.AlterField(
            model_name='quizcatalog',
            name='course',
            field=models.CharField(default='general paper', max_length=255),
        ),
        migrations.AlterField(
            model_name='quizcatalog',
            name='date',
            field=models.CharField(default='Sat Mar 21 23:01:38 2020', max_length=25),
        ),
    ]
